title: Diapason Produções
description: > # this means to ignore newlines until "baseurl:"
  Transformando sonhos em áudio, filmes e fotografias desde 2012, a
  Diapason sabe que som e imagem são meios muito poderosos de comunicação.
  Nossos clientes contam com equipe e estúdios atualizados, versáteis e
  altamente qualificados em equipamentos e estrutura. Mais que isto,
  profissionais com conhecimento e experiência para fazer o melhor uso
  desta tecnologia e traduzir suas emoções em produções audiovisuais especiais
  e únicas, levando sua história para ser sentida na pele.

# DEV
baseurl: "" # the subpath of your site, e.g. /blog
# PRODUCTION
# baseurl: "diapasonproducoes.github.io/" # the subpath of your site, e.g. /blog
url: "http://www.diapason.com.br"

social:
  - title: instagram
    url: http://www.instagram.com/diapasonproducoes
    icon: fa-instagram
  - title: facebook
    url: http://www.facebook.com/DiapasonProducoes
    icon: fa-facebook-official
  - title: youtube
    url: https://www.youtube.com/diapasonproducoes
    icon: fa-youtube-square
  - title: flickr
    url: https://www.flickr.com/photos/diapason
    icon: fa-flickr
  - title: email
    url: mailto:contato@diapason.com.br
    icon: fa-envelope-square


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-redirect-from
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
    style: :compressed
    sass_dir: _sass

lang: 'pt-BR'
