title: Diapason Produções
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/diapason-pages" # the subpath of your site, e.g. /blog
url: "http://www.diapasonproducoes.com.br"

social:
  - title: instagram
    url: http://www.instagram.com/diapasonproducoes
    icon: fa-instagram
  - title: facebook
    url: http://www.facebook.com/diapasonproducoes
    icon: fa-facebook-official
  - title: twitter
    url: http://www.twitter.com/diapasonproducoes
    icon: fa-twitter-square
  - title: youtube
    url: https://www.youtube.com/user/diapasonproducoes
    icon: fa-youtube-square
  - title: email
    url: mailto:diapasonproducoes@diapasonproducoes.com.br
    icon: fa-envelope-square


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-redirect-from
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
    style: :compressed
    sass_dir: _sass

lang: 'pt-BR'
